[providers]
providers = ['node', 'python']

[phases.setup]
nixPkgs = ['python311', 'nodejs_20']

[phases.install]
cmds = [
  'npm install',
  'pip install -r backend/requirements.txt'
]

[phases.build]
cmds = [
  'npm run build'
]

[start]
cmd = 'python backend/main.py'

